server:
    port: 8080 

spring:
    cassandra:
        contact-points: 127.0.0.1 # Cassandra 集群节点地址（可配置多个，用逗号分隔）
        port: 9042 # 端口号
        local-datacenter: datacenter1 # 必须与集群配置的数据中心名称一致（大小写敏感）
    ai:
        deepseek:
            api-key: sk-3525b089f64545ff84a615f3b3e071c3 # ?? DeepSeek Api Key, ??????
            base-url: https://api.deepseek.com # DeepSeek ??? URL, ???????? api.deepseek.com
            chat:
                options:
                    model: deepseek-chat # ??????
                    temperature: 0.8 # ???
        ollama:
            base-url: http://localhost:11434 # Ollama ???????, 11434 ??? Ollama ???????
            chat:
                options: # ????
                    model: qwen3:1.7b # ?? Ollama ???????????????????????? 14b
                    temperature: 0.7 # ???
        openai:
            base-url: https://dashscope.aliyuncs.com/compatible-mode # OpenAI ???????????????????
            api-key: sk-800dbad219764571ab1d056c09be5fed  # ???????? API Key, ??????
            chat:
                options:
#                    model: qwen-omni-turbo # ????
                    model: qwen-turbo
                    temperature: 0.7 # ???
        chat:
            memory:
                repository:
                    cassandra:
                        keyspace: xiaoha_ai_robot # 指定存储聊天记忆的 Keyspace（类似数据库名）
                        table: t_ai_chat_memory # 表名
                        time-to-live: 1095d # 数据的自动过期时间（1095天 ≈ 3年）
                        initialize-schema: true  # 自动初始化表结构
        mcp:
            client:
                stdio:
                    servers-configuration: classpath:/mcp-servers-config.json # 指定 MCP 服务的配置文件路径
                toolcallback:
                    enabled: true # 开启 MCP 客户端的工具回调（Tool Callback）功能
logging:
    level:
        org.springframework.ai.chat.client.advisor: debug